### ISSUE TITLE
Uknown log format

### ISSUE THREAD

**Issue by Joeri94** [gilbN/geoip2influx#1]
Hello,

Im pretty new to the world of webistes and logging, im gosting my own website now and tried to use your awesome plugin.
bet i keep getting these errors.
<img width="931" alt="afbeelding" src="https://user-images.githubusercontent.com/45860400/88648780-9a0f8880-d0c7-11ea-8bf4-a9cd8639563c.png">

this is my .conf file 
<img width="931" alt="afbeelding" src="https://user-images.githubusercontent.com/45860400/88649200-f5da1180-d0c7-11ea-9977-37c2022df002.png">

what  am i doing wrong? could you give me a push in the right way?

Thank you for your work and help.

with kind regards.

**Comment by gilbN** [comment]
Try and move the log_format above the access_log line.

**Comment by Joeri94** [comment]
Thank you verry much, that worked for me ! 

everything seems fine now but i still got no quereries in influxdb :(

**Comment by Joeri94** [comment]
`28/Jul/2020 12:41:06 :: INFO :: Starting geoip2influx..
28/Jul/2020 12:41:06 :: DEBUG :: Variables set:
 geoip_db_path             :: /config/geoip2db/GeoLite2-City.mmdb
 -e LOG_PATH               :: /config/log/nginx/access.log
 -e INFLUX_HOST            :: 192.168.2.18
 -e INFLUX_HOST_PORT       :: 8086
 -e INFLUX_DATABASE        :: geoip2influx
 -e INFLUX_RETENTION       :: 7d
 -e INFLUX_SHARD           :: 1d
 -e INFLUX_USER            :: root
 -e INFLUX_PASS            :: root
 -e GEO_MEASUREMENT        :: geoip2influx
 -e LOG_MEASUREMENT        :: nginx_access_logs
 -e SEND_NGINX_LOGS        :: true
 -e GEOIP2INFLUX_LOG_LEVEL :: DEBUG
28/Jul/2020 12:41:06 :: DEBUG :: Found: /config/log/nginx/access.log
28/Jul/2020 12:41:06 :: DEBUG :: Found: /config/geoip2db/GeoLite2-City.mmdb
28/Jul/2020 12:41:06 :: DEBUG :: Testing InfluxDB connection
28/Jul/2020 12:41:06 :: DEBUG :: Starting new HTTP connection (1): 192.168.2.18:8086
28/Jul/2020 12:41:06 :: DEBUG :: http://192.168.2.18:8086 "GET /ping HTTP/1.1" 204 0
28/Jul/2020 12:41:06 :: DEBUG :: Influxdb version: 1.8.1
28/Jul/2020 12:41:06 :: DEBUG :: http://192.168.2.18:8086 "GET /query?q=SHOW+DATABASES&db=geoip2influx HTTP/1.1" 200 None
28/Jul/2020 12:41:06 :: DEBUG :: Found database: geoip2influx
28/Jul/2020 12:41:06 :: DEBUG :: Regex is matching /config/log/nginx/access.log continuing...
28/Jul/2020 12:41:06 :: INFO :: Starting log parsing
`

**Comment by gilbN** [comment]
Make sure you are accessing from outside your network. It won't log internal ips

**Comment by Joeri94** [comment]
i am, but i got no queries in influx. database is created, connection works. i dont uderstand it anymore.

**Comment by gilbN** [comment]
is the access.log logging new entries?

**Comment by Joeri94** [comment]
acces.log is logging new entries i use unraid als hypervisor. 
`
Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
NGINX_LOG_PATH=
INFLUX_HOST=192.168.2.18
INFLUX_HOST_PORT=8086
INFLUX_DATABASE=ip_log
INFLUX_USER=root
INFLUX_PASS=root
INFLUX_RETENTION=
INFLUX_SHARD=
GEO_MEASUREMENT=
LOG_MEASUREMENT=geo2ip
SEND_NGINX_LOGS=
GEOIP2INFLUX_LOG_LEVEL=debug
MAXMINDDB_LICENSE_KEY=LZtZUCynbAeZFQho

[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.`
this is the log form the docker container.

**Comment by gilbN** [comment]
Hm, can you share the docker run command?

**Comment by Joeri94** [comment]
I run this from unraid so it used templates 
Everything what is set you can see under variables set in the log above.

**Comment by gilbN** [comment]
Try and tail the `/config/log/nginx/access.log` from inside the container to see if it gets updated.

**Comment by Joeri94** [comment]
I think that I know the issue by now.
I use an reverse proxy to get to nginx.
Nginx only sees the ip of the reverse proxy (the local one) so it won't work for this setup.

**Comment by gilbN** [comment]
I do too. 

Use set real ip. 
Example:
```
set_real_ip_from 172.17.0.0/16;
real_ip_recursive on;
```

**Comment by Joeri94** [comment]
Where do I meet to put the code?
In nginx Proxy or nginx webserver.
Sorry  I'm a little new here.

**Comment by Joeri94** [comment]
Fixed with help of the dev on discord !
