### ISSUE TITLE
grafana dashboard ALL selection not working?

### ISSUE THREAD

**Issue by poldim** [GilbN/geoip2influx#11]
Hey,
I couldn't find anything after searching for this.  It seems like the ALL selection in the drop-down isn't doing what it should.  I have the default of all selected and no data gets displayed.  Then if I go in and make selections instead of all data shows up.  I've also tried modifying the query as below and this works to display some data as well.

Original: `SELECT sum("bytes_sent") FROM "nginx_access_logs" WHERE ("ip" !~ /^$excluded_ip$/ AND "city" =~ /^$city$/ AND "country_code" =~ /^$country_code$/ AND "country_name" =~ /^$country$/ AND "host" =~ /^$domain$/) AND $timeFilter GROUP BY time($__interval) fill(null)`
Modified: `SELECT sum("bytes_sent") FROM "nginx_access_logs" WHERE ("ip" !~ /^$excluded_ip$/) AND $timeFilter GROUP BY time($__interval) fill(null)`

I also noticed clicking all doesn't actually select all of the ones below, just selects the one all box:
![image](https://user-images.githubusercontent.com/16869713/151049521-3f44d2fa-5cab-4884-ac48-de730251d302.png)

Clicking on selected twice does place a check into all of the entries, but I imagine this would have to be done frequently to update all of the selections
![image](https://user-images.githubusercontent.com/16869713/151049675-52f5c370-fecc-460e-8269-4625a6f68ae1.png)

**Comment by GilbN** [comment]
Hm

> Hey, I couldn't find anything after searching for this. It seems like the ALL selection in the drop-down isn't doing what it should. I have the default of all selected and no data gets displayed. Then if I go in and make selections instead of all data shows up. I've also tried modifying the query as below and this works to display some data as well.
> 
> Original: `SELECT sum("bytes_sent") FROM "nginx_access_logs" WHERE ("ip" !~ /^$excluded_ip$/ AND "city" =~ /^$city$/ AND "country_code" =~ /^$country_code$/ AND "country_name" =~ /^$country$/ AND "host" =~ /^$domain$/) AND $timeFilter GROUP BY time($__interval) fill(null)` Modified: `SELECT sum("bytes_sent") FROM "nginx_access_logs" WHERE ("ip" !~ /^$excluded_ip$/) AND $timeFilter GROUP BY time($__interval) fill(null)`
> 
> I also noticed clicking all doesn't actually select all of the ones below, just selects the one all box: ![image](https://user-images.githubusercontent.com/16869713/151049521-3f44d2fa-5cab-4884-ac48-de730251d302.png)
> 
> Clicking on selected twice does place a check into all of the entries, but I imagine this would have to be done frequently to update all of the selections ![image](https://user-images.githubusercontent.com/16869713/151049675-52f5c370-fecc-460e-8269-4625a6f68ae1.png)

Hm, I just spun up a new instance and seems to be working for me. 

https://selfhosted.app/f3c10/rofeMUPE06.mp4

**Comment by poldim** [comment]
Bummer, ok, I'll dig on my end.  Thanks for checking.
