### ISSUE TITLE
Add Support for influxdb 2 or 3

### ISSUE THREAD

**Issue by GilbN** [GilbN/geoip2influx#21]

**Comment by GilbN** [comment]
Support added in branch https://github.com/GilbN/geoip2influx/tree/influxdb2-support

**Comment by ain-soph** [comment]
~~Hi, does that mean `Dashboard currently only supports InfluxDB 1.8.x.` in the README is no longer valid?~~

Update: tested and seems working with `2.x` now. Please update the readme
