### ISSUE TITLE
Get error message  when influxdb docker updated 5 days ago

### ISSUE THREAD

**Issue by leo15dev** [gilbN/geoip2influx#3]
It work well until the  influxdb docker image ( influxdb:latest ) updated 5 days ago. 

Here is the error message:
GEOIP2INFLUX 25/Feb/2021 12:09:46 :: INFO :: Starting geoip2influx..
GEOIP2INFLUX 25/Feb/2021 12:09:46 :: CRITICAL :: Error getting database list! Please check your InfluxDB configuration.
Error: 401: {"code":"unauthorized","message":"Unauthorized"}
 
Thank you!

**Comment by gilbN** [comment]
Switch to the 1.8 tag

**Comment by leo15dev** [comment]
Solved! Thank you!
